{% set name = "csdms-topoflow-evap-evap_energy-balance" %}
{% set version = "3.4" %}

package:
  name: {{ name }}
  version: {{ version }}

source:
  git_url: https://github.com/csdms/topoflow-bridge

requirements:
  build:
    - bmi-babel
    - topoflow
  run:
    - bmi-babel
    - topoflow

test:
  requires:
    - pymt
    - bmi-tester

about:
  home: http://csdms.colorado.edu/wiki/Model_help:TopoFlow-Evaporation-Energy_Balance
  license: Apache
  summary: |
    The EvapEnergyBalance component, a part of the spatially distributed
    hydrologic model TopoFlow, uses the <em>energy balance</em> method of
    estimating water losses from the Earth's surface due to evaporation.
