language: generic
os:
- linux
- osx
env:
  global:
  - CONDA_PREFIX=$HOME/miniconda
  - MINICONDA_URL_BASE="http://repo.continuum.io/miniconda/Miniconda-latest"
  - TRAVIS_PYTHON_VERSION="2.7"
  - secure: qLRa7aO238hGNspcKBO4/sLiesfbDuGOUf+2130Ye7KS6aOH/wZWktwTl/qfUu+38c5+7LXqm6X+LT1GuZwn9BLc0s9YwV+pWQ0TORNHAFFgXARjdiazSzOD0FD20aEXXqO2bf4Behi9ftYVjgICqDKryRo3S8OvpoF/a9wxk6IFFCMHhoDLZqhBjiE+N60DH4cXQLSAy1v9lj0+sRXC+FZtfnaw2HQ4wEFybXMh/PUrXVPHrTEaz/Ix2dscoZPIPPj66J9Gi3kq/AXkcMl8dS2wyZkp7BxyFXkyb+Oo0PaH5iBS73/aB846HoI0fyKfRO5D/zD6LSkygmkHZaOGNXYpImWE1MVWRz6Ysp2PvsZ3lyNrk/HYZPViHTAnQPUPWZomJMFjF3uydE6M7nuUddtqAAb1L/ml5qrVqKtxhm2G3BFmXY1eVvrAFyrc/PL2LQxzbVHPScnq56hYvTcIQkQ0oyjLKKAhhN5oCmlnUmE/syrRZ860jNdc1AuIXlIwGYhFqP/Ems+bHh4cn+zrdPWojQfuwT3W8w8KbTXexpG6CNOZ0DvPJ7959/s8EqVdsUqbdYBIxxr896+RP35dYNc6upcD/n9Dhpzu/hK1dmcHmUy23wkfrDT5YSgSjDaG3JnaV7mXMdIunFTBhtRrwazT9/uBSc0W1ssCUTmW1Uo=
sudo: false
before_install:
- |
  if [[ $TRAVIS_OS_NAME == "osx" ]]; then
    brew remove --force $(brew list)
    brew cleanup -s
    rm -rf $(brew --cache)
  fi
install:
- |
  if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then
    OS="MacOSX-x86_64"
  else
    OS="Linux-x86_64"
  fi
- curl $MINICONDA_URL_BASE-$OS.sh > $HOME/minconda.sh
- bash $HOME/minconda.sh -b -p $CONDA_PREFIX
- export PATH="$CONDA_PREFIX/bin:$PATH"
- hash -r
- conda config --set always_yes yes --set changeps1 no
- conda install python=$TRAVIS_PYTHON_VERSION
- conda install -q conda-build anaconda-client coverage sphinx
script:
- conda build ./recipe -c csdms-stack -c conda-forge
after_success:
- curl https://raw.githubusercontent.com/csdms/ci-tools/master/anaconda_upload.py
  > $HOME/anaconda_upload.py
- echo $ANACONDA_TOKEN | python $HOME/anaconda_upload.py ./recipe --channel=main --org=csdms-stack
  --token=-
